logging:
  level:
    root: INFO
#重写logback模版 默认：common-logging下的logback-spring.xml
#  config: classpath:logback-test.xml

spring:
  datasource:
    dynamic:
      primary: master
      strict: false
      datasource:
        master:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://localhost:3306/nacos_config?characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&verifyServerCertificate=false&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8
          username: nacos
          password: nacos
  #        slave_1:
  #          driver-class-name: com.mysql.cj.jdbc.Driver
  #          url: jdbc:mysql://123.56.170.25:3306/tavern_home?characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&verifyServerCertificate=false&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8
  #          username: root
  #          password: 123456
  redis:
    host: localhost
    port: 6379
    password: root
    database: 0
    timeout: 5000

  mail:
    host: smtp.163.com
    port: -1
    username: minlc1024@163.com
    password: FMBHOGEPRJONSQQQ
