logging:
  level:
    root: INFO
  # 重写logback模版 默认：common-logging下的logback-spring.xml
  config: classpath:logback-spring.xml

spring:
  #  datasource:
  #    dynamic:
  #      primary: master
  #      strict: false
  #      datasource:
  #        master:
  #          driver-class-name: com.mysql.cj.jdbc.Driver
  #          url: jdbc:mysql://localhost:3306/nacos_config?characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&verifyServerCertificate=false&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8
  #          username: nacos
  #          password: nacos
  #        slave_1:
  #          driver-class-name: com.mysql.cj.jdbc.Driver
  #          url: jdbc:mysql://123.56.170.25:3306/tavern_home?characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&verifyServerCertificate=false&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8
  #          username: root
  #          password: 123456

  redis:
    host: localhost
    port: 6379
    password: root
    database: 0
    timeout: 5000

  cloud:
    stream:
      # 默认绑定器配置
      default-binder: rabbit

      # 绑定器配置
      binders:
        rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: test
                password: test
                virtual-host: /

      # 绑定配置
      bindings:
        message-output:
          destination: default.exchange
          group: default.queue
          content-type: application/json
          binder: rabbit
          producer:
            required-groups: default.queue # 确保消费者组存在

        delayed-output:
          destination: delayed.exchange
          group: delayed.queue
          binder: rabbit

        direct-output:
          destination: direct.exchange
          group: direct.queue
          binder: rabbit

        topic-output:
          destination: topic.exchange
          content-type: application/json
          binder: rabbit

        # RabbitMQ特定配置
      rabbit:
        bindings:
          message-output:
            producer:
              exchange-type: topic # 消息模式：topic
              delayed-exchange: false # 不自动声明延迟交换机
              declare-exchange: false # 不自动声明交换机
              bind-queue: false # 不自动绑定队列

          delayed-output:
            producer:
              exchange-type: topic
              declare-exchange: false
              bind-queue: false
              routing-key-expression: "'delayed.routing.key'" # 静态路由键

          direct-output:
            producer:
              exchange-type: direct # 消息模式：direct
              declare-exchange: false
              bind-queue: false
              routing-key-expression: "'direct.routing.key'" # 静态路由键

          topic-output:
            producer:
              exchange-type: topic
              declare-exchange: false
              bind-queue: false
              routing-key-expression: headers['routingKey'] # 动态路由键

  # RabbitMQ原生配置
  rabbitmq:
    dynamic: false
    template:
      retry:
        enabled: true
        max-attempts: 3
        initial-interval: 1000ms
    listener:
      simple:
        acknowledge-mode: auto
        retry:
          enabled: true
          max-attempts: 3
          stateless: true

  mail:
    host: smtp.163.com
    port: -1
    username: minlc1024@163.com
    password: FMBHOGEPRJONSQQQ
    properties:
      fromName: minliangchao

aicyi:
  sms:
    enabled: true
    username: AC56dfa4c2d3284693ddebd2834b499486
    password: 2589e1619a40d8e5bb565b49563fb80d
    from: +19472182422
