logging:
  level:
    root: INFO

spring:
  datasource:
    dynamic:
      primary: master
      strict: false
      datasource:
        master:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://localhost:3306/nacos_config?characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&verifyServerCertificate=false&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8
          username: nacos
          password: nacos
  redis:
    host: localhost
    port: 6379
    password: root
    database: 0
    timeout: 5000

  cloud:
    stream:
      # 默认绑定器配置
      default-binder: rabbit

      # 绑定器配置
      binders:
        rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: test
                password: test
                virtual-host: /

      # 绑定配置
      bindings:
        message-input:
          destination: default.exchange
          group: default.queue
          content-type: application/json
          binder: rabbit
          consumer:
            concurrency: 3 # 最大并发数
            max-attempts: 3 # 最大重试次数
            back-off-initial-interval: 1000 # 重试间隔(ms)

        delayed-input:
          destination: delayed.exchange
          group: delayed.queue
          content-type: application/json
          binder: rabbit

        direct-input:
          destination: direct.exchange
          group: direct.queue
          binder: rabbit

        orderEvents-in-0:
          destination: topic.exchange
          group: order-service
          binder: rabbit

        systemLogs-in-0:
          destination: topic.exchange
          group: log-service
          binder: rabbit

        # RabbitMQ特定配置
      rabbit:
        bindings:

          message-input:
            consumer:
              queue-name-group-only: true # 队名列等于组名，默认队列名等于交换机+组名
              durable-subscription: true # 持久化订阅
              exchange-auto-delete: false # 不自动删除交换机
              declare-exchange: false # 不自动声明交换机
              bind-queue: false # 不自动绑定队列

          delayed-input:
            consumer:
              queue-name-group-only: true
              durable-subscription: true
              declare-exchange: false
              bind-queue: false

          direct-input:
            consumer:
              queue-name-group-only: true
              durable-subscription: true
              declare-exchange: false
              bind-queue: false

          orderEvents-in-0:
            consumer:
              durable-subscription: true
              declare-exchange: false
              bind-queue: false

          systemLogs-in-0:
            consumer:
              durable-subscription: true
              declare-exchange: false
              bind-queue: false

  # RabbitMQ原生配置
  rabbitmq:
    dynamic: false
    template:
      retry:
        enabled: true
        max-attempts: 3
        initial-interval: 1000ms
    listener:
      simple:
        acknowledge-mode: auto
        retry:
          enabled: true
          max-attempts: 3
          stateless: true

  mail:
    host: smtp.163.com
    port: -1
    username: minlc1024@163.com
    password: FMBHOGEPRJONSQQQ
    properties:
      fromName: minliangchao

aicyi:
  sms:
    enabled: true
    username: AC56dfa4c2d3284693ddebd2834b499486
    password: 2589e1619a40d8e5bb565b49563fb80d
    from: +19472182422